// Generated by https://quicktype.io

export interface Category {
    categoryID:   string;
    categoryName: string;
    categoryCodename: string;
    productCount: string;
    product?:      ProductinCat[] | null;
}

export interface ProductinCat {
    productsID:   string;
    productsName: string;
}
